apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubesphere
    component: ks-sample-dev
    tier: backend
  name: ks-sample-dev
  namespace: java-springboot
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: kubesphere
      component: ks-sample-dev
      tier: backend
  template:
    metadata:
      labels:
        app: kubesphere
        component: ks-sample-dev
        tier: backend
    spec:
      imagePullSecrets:
        - name: aliyun-docker-hub
      containers:
        - env:
            - name: REDIS_HOST
              value: redis-ahwrd7
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/devops-java-simple:$BUILD_NUMBER
          imagePullPolicy: Always
          name: ks-sample
          ports:
            - containerPort: 8090
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
