apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: java-springboot
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      imagePullSecrets:
        - aliyun-docker-hub
      containers:
      - name: myapp
        image: $REGISTRY/$DOCKERHUB_NAMESPACE/devops-java-simple:$BUILD_NUMBER
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
