apiVersion: v1
kind: Deployment
metadata:
  labels:
    app: java-test
    component: test
    tier: test
  name: ks-sample-dev
  namespace: many-cluster
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: java-test
      component: test
      tier: test
  template:
    metadata:
      labels:
        app: java-test
        component: test
        tier: test
    spec:
      imagePullSecrets:
        - name: aliyun-docker-hub
      containers:
        - env:
            - name: REDIS_HOST
              value: redis-ahwrd7
          image: $REGISTRY:30443/$DOCKERHUB_NAMESPACE/devops-java-simple:$BUILD_NUMBER
          imagePullPolicy: Always
          name: ks-sample
          ports:
            - containerPort: 8090
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
